language: python
python:
  - 3.4
# command to install dependencies
install:
  - pip install requests==2.18.3 httpbin==0.7.0 gunicorn==19.7.1 coveralls
# start local http server in background, give it a few seconds to start
before_script:
  - gunicorn httpbin:app &
  - sleep 3
# command to run tests
script:
  - cd .. && coverage run --source=Requester.core -m unittest Requester.tests.core -v
after_success:
  - coveralls
